commuto_swap_error_messages = {
    "e0": "_serviceFeePool address cannot be zero",
    "e1": "_daiAddress cannot be zero address",
    "e2": "_usdcAddress cannot be zero address",
    "e3": "_busdAddress cannot be zero address",
    "e4": "_usdtAddress cannot be zero address",
    "e5": "An offer with the specified id already exists",
    "e6": "The minimum swap amount must be greater than zero",
    "e7": "The maximum swap amount must be >= the minimum swap amount",
    "e8": "The security deposit must be at least 10% of the minimum swap amount",
    "e9": "Service fee amount must be greater than zero",
    "e10": "Offers can only be created for the most recent protocol version",
    "e11": "You must specify a supported stablecoin",
    "e12": "You must specify a supported direction",
    "e13": "Token allowance must be >= required amount",
    "e14": "Token transfer to Commuto Protocol failed",
    "e15": "An offer with the specified id does not exist",
    "e16": "Offer is taken and cannot be canceled",
    "e17": "Offers can only be canceled by offer maker",
    "e18": "Offer has invalid direction",
    "e19": "Token transfer failed",
    "e20": "The offer with the specified id has already been taken",
    "e21": "Maker addresses must match",
    "e21.1": "Maker interface ids must match",
    "e22": "Stablecoin types must match",
    "e23": "Lower bounds must match",
    "e24": "Upper bounds must match",
    "e25": "Security deposit amounts must match",
    "e26": "Swap amount must be >= lower bound of offer amount",
    "e27": "Swap amount must be <= upper bound of offer amount",
    "e28": "Directions must match",
    "e29": "Prices must match",
    "e30": "Payment methods must match",
    "e31": "Protocol versions must match",
    "e32": "Maker extra data must match",
    "e33": "A swap with the specified id does not exist",
    "e34": "Payment sending has already been reported for swap with specified id",
    "e35": "Payment sending can only be reported by buyer",
    "e36": "Swap has invalid direction",
    "e37": "Payment sending has not been reported for swap with specified id",
    "e38": "Payment receiving has already been reported for swap with specified id",
    "e39": "Payment receiving can only be reported by seller",
    "e40": "Payment receiving has not been reported for swap with specified id",
    "e41": "Buyer has already closed swap",
    "e42": "Service fee transfer failed",
    "e43": "Seller has already closed swap",
    "e44": "Only swap maker or taker can call this function",
    "e45": "Only owner can set fiat currency support",
    "e46": "Fiat currency must be supported in supportedFiats",
    "e47": "Fiat currencies must match"
}
