commuto_error_messages = {
    "e0": "More blocks must be mined before a revenue distribution snapshot can be created",
    "e1": "Only the current primary timelock can set dispute agent activity state",
    "e2": "Dispute agent address cannot be the zero address",
    "e3": "Selected dispute agents must be active",
    "e4": "Dispute cannot be raised if maker or taker has already closed",
    "e5": "An offer with the specified id already exists",
    "e6": "The minimum swap amount must be greater than zero",
    "e7": "The maximum swap amount must be >= the minimum swap amount",
    "e8": "The security deposit must be at least 10% of the maximum swap amount",
    "e9": "Service fee amount must be greater than zero",
    "e10": "Offers can only be created for the most recent protocol version",
    "e11": "You must specify a supported stablecoin",
    "e12": "You must specify a supported direction",
    "e13": "Token allowance must be >= required amount",
    "e14": "Token transfer to Commuto Protocol failed",
    "e15": "An offer with the specified id does not exist",
    "e16": "Offer is taken and cannot be mutated",
    "e17": "Offers can only be mutated by offer maker",
    "e18": "Swap does not require filling",
    "e19": "Token transfer failed",
    "e20": "The offer with the specified id has already been taken",
    "e21": "Maker addresses must match",
    "e21.1": "Maker interface ids must match",
    "e22": "Stablecoins must match",
    "e23": "Lower bounds must match",
    "e24": "Upper bounds must match",
    "e25": "Security deposit amounts must match",
    "e26": "Swap amount must be >= lower bound of offer amount",
    "e27": "Swap amount must be <= upper bound of offer amount",
    "e28": "Directions must match",
    "e29": "Prices must match",
    "e30": "Settlement method must be accepted by maker",
    "e31": "Protocol versions must match",
    "e32": "Maker-as-seller swap cannot be filled if swap is disputed",
    "e33": "A swap with the specified id does not exist",
    "e34": "Payment sending has already been reported for swap with specified id",
    "e35": "Payment sending can only be reported by buyer",
    "e36": "Swap has invalid direction",
    "e37": "Payment sending has not been reported for swap with specified id",
    "e38": "Payment receiving has already been reported for swap with specified id",
    "e39": "Payment receiving can only be reported by seller",
    "e40": "Payment receiving has not been reported for swap with specified id",
    "e41": "Buyer has already closed swap",
    "e42": "Service fee transfer failed",
    "e43": "Seller has already closed swap",
    "e44": "Only swap maker or taker can call this function",
    "e45": "Only the current primary timelock can set settlement method support",
    "e46": "Settlement method must be supported",
    "e47": "Only maker and seller can fill swap",
    "e48": "The swap must be filled before payment is sent",
    "e49": "Only the current primary timelock can set stablecoin support",
    "e50": "Payment sending cannot be reported if swap is disputed",
    "e51": "Payment receiving cannot be reported if swap is disputed",
    "e52": "Swap cannot be closed if it is disputed",
    "e53": "Dispute cannot be raised for an already-disputed swap",
    "e54": "Swap doesn't exist or isn't disputed",
    "e55": "Only a dispute agent selected for the swap can propose a resolution",
    "e56": "Total payout amount must equal total amount paid in minus service fees",
    "e57": "Only swap maker or taker can react to resolution proposal",
    "e58": "Can't react with no reaction",
    "e59": "Maker can't react to resolution proposal more than once",
    "e60": "Taker can't react to resolution proposal more than once",
    "e61": "Two matching resolutions must be proposed before reaction is allowed",
    "e62": "A resolution proposal cannot be submitted if the maker or taker has already reacted",
    "e63": "Only maker and taker can close disputed swap",
    "e64": "Disputed swap closure requires proposal acceptance by maker and taker",
    "e65": "Maker cannot close disputed swap more than once",
    "e66": "Taker cannot close disputed swap more than once",
    "e67": "Confiscated amount transfer failed",
    "e68": "A resolution cannot be proposed for an escalated swap",
    "e69": "A reaction cannot be submitted for an escalated swap",
    "e70": "closeEscalatedSwap can only be called for escalated swaps",
    "e71": "More blocks must be mined before swap can be escalated",
    "e72": "Resolution proposal must be rejected to escalate dispute because of rejection",
    "e73": "Dispute can't be escalated for lack of dispute agent response if dispute agents have agreed on resolution proposal",
    "e74": "Dispute cannot be escalated for lack of counterparty reaction if counterparty has reacted",
    "e75": "Only maker or taker can escalate disputed swap",
    "e76": "Dispute cannot be escalated for lack of counterparty reaction if caller has not reacted",
    "e77": "All dispute agents must be different",
    "e78": "Cannot escalate dispute if dispute has already been escalated",
    "e79": "Only the current primary timelock can call this function",
    "e80": "Only the current primary timelock or dispute resolution timelock can call this function",
    "e81": "Total payout amount must equal total without spent service fees",
    "e82": "Token transfer to maker failed",
    "e83": "Token transfer to taker failed",
}
